### ISSUE TITLE
USER STORY : Reset password if forgotten

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#13]
As a **Site User** I am able to **Reset My Password** to **change my password if forgotten**.

**Acceptance Criteria :**

When I visit login page then I have the option to reset my password via provided link and email with reset link is sent to me.

**Tasks :**

- [x] Register with mail client (Gmail) 
- [x] Set up all relevant settings for sending emails in `settings.py`
- [x] Test functinality with valid credentails
- [x] Test functionality with invalid credentials

**Epic :**
[EPIC 3](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/10)

**Comment by tomik-z-cech** [comment]
This was done in commit [5a19fd0](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/5a19fd0b165c1ddda2e5cee6dc27f62fb5d4c213).
