### ISSUE TITLE
USER STORY : Log Out

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#14]
As a **Site User**, I am able to log out to **leave the site functions for registered users**.

**Acceptance Criteria :**

*1.Registered user :*
When I am logged in then I am able to logout.

*2.Not registered user :*
Don't have that option.

**Tasks :**

- [x] Create a log out link in base.html
- [x] Create if statement `{% if user.is_authenticated %}` in `base.html`
- [x] Test functionality with valid credentials

**Epic :**
[EPIC 3](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/10)

**Comment by tomik-z-cech** [comment]
This was done in commit [5a19fd0](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/5a19fd0b165c1ddda2e5cee6dc27f62fb5d4c213).
