### ISSUE TITLE
USER STORY : Categories section

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#16]
As a **Business Owner**, I have option to **do full CRUD** with item categories in order to manage my shop.

**Acceptance Criteria :**

*Staff/SuperUser :*

When I log in with my credentials then I am able to navigate to admin tools section to perform CRUD on shop categories.

*Users with no staff or Superuser rank :*

Not able to access that functinality.

**Tasks :**

- [x] Create categories views
- [x] Update `urls.py` in owner app 
- [x] Create forms needded
- [x] Create templates for reading, creating, editing and deleting categories
- [x] Create and register widget for submitting category image
- [x] Test functionality as Site Admin

**Epic :**
[EPIC 4](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/15)

**Comment by tomik-z-cech** [comment]
This was done in commit [7750783](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/7750783f78551c3a812957ce6be6d23397cf471a).
