### ISSUE TITLE
USER STORY : Items section

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#17]
As a **Business Owner**, I have option to **do full CRUD** with items in order to manage products sold in my shop.

**Acceptance Criteria :**

*Staff/SuperUser :*

When I log in with my credentials then I am able to navigate to admin tools section to perform CRUD on shop items.

*Users with no staff or Superuser rank :*

Not able to access that functinality.

**Tasks :**

- [x] Create items views
- [x] Update `urls.py` in owner app 
- [x] Create forms needded
- [x] Create templates for reading, creating, editing and deleting items
- [x] Create and register widget for submitting item images
- [x] Test functionality as Site Admin

**Epic :**
[EPIC 4](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/15)

**Comment by tomik-z-cech** [comment]
This was done in commit [bd40bbf](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/bd40bbfb7c2625bfb3903df6d746aaf481804568).
