### ISSUE TITLE
USER STORY : Set Up GitHub Repository

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#2]
As a **Site Developer**, I need to set-up a repository on GitHub platform to be able to have control over versions of project.

**Acceptance Criteria : **

Working GitHub repository.

**Tasks :**

**Tasks :**
- [x] Create new repository - PP5 - Ohm-Azing Components
- [x] Create project for the same repository
- [x] Create labels for importance (Must, Should, Could, Won't Have & Bugs)
- [x] Create labels for Story Points in Fibonacci Sequence (1,2,3,5,8,13,21)
- [x] Create Epic's
- [x] Create User Stories

**Epic :**
[EPIC 1](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/1)

**Comment by tomik-z-cech** [comment]
This was done in commit [1861fb4](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/1861fb476f7bddef5536c8cea1f3afc96ba70731).
