### ISSUE TITLE
USER STORY : Comments section

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#20]
As a **Business Owner**, I have option to approve/delete comments to ensure no inapproproate content on the project page.

**Acceptance Criteria :**

*Staff/SuperUser :*

When I log in with my credentials then I am able to navigate to admin tools section approve/delete comments.

*Users with no staff or Superuser rank :*

Not able to access that functinality.

**Tasks :**

- [x] Create comments views
- [x] Update `urls.py` in owner app 
- [x] Create templates for vieving, approving and deleting comments
- [x] Test functionality as Site Admin

**Epic :**
[EPIC 4](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/15)

**Comment by tomik-z-cech** [comment]
This was done in commit [797af69](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/797af69ea601041f30210b958552650628bdd9b7).
