### ISSUE TITLE
USER STORY : Favicon & Title

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#23]
As a **Site User** I woul like to be **able to differenciate this site** from other sites opened in my browser, in order of **easy navigation**.

**Acceptance Criteria :**

When I navogate to the site, then I am clarly served with FavIcon and title of the site  .

**Tasks :**

- [x] Create a FavIcon from logo
- [x] Register favicon in `base.html` template
- [x] Regsiter site title with `{% block nav_name %}{% endblock %}`
- [x] Equip each template that extends `base.html` with the same `{% block nav_name %}{% endblock %}` including the title of sub page
- [x] Test functionality as Site User and Site Admin

**Epic :**
[EPIC 5](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/22)

**Comment by tomik-z-cech** [comment]
This was done in commit [8f235c7](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/8f235c7c3e6871b1f19ee4d28bcebeae9bc41171).
