### ISSUE TITLE
USER STORY : Header

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#24]
As a **Site User** I want to be able to navigate easily through-out the site.

**Acceptance Criteria :**

When I navigate to the site, I am able to see header with logo and  icons for menu, vault and wishlist (if logged in).

**Tasks :**

- [x] Create `header.html` template
- [x] Include the template in `base.html` 
- [x] Include logo and links for menu, vault and wishlist
- [x] Create logic for not loggedin users / logged in users / supersusers
- [x] Test functionality as Not Logged in User / Logged in User / Site Admin

**Epic :**
[EPIC 5](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/22)

**Comment by tomik-z-cech** [comment]
This was done in commit [5a19fd0](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/5a19fd0b165c1ddda2e5cee6dc27f62fb5d4c213).
