### ISSUE TITLE
USER STORY : Footer

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#25]
As a **Site User** I want to be able to **find useful info on the bottom of the site** in order not to **scroll and search too much around**.

**Acceptance Criteria :**

When I navigate to the site, I am able to see footer with basic contact details, link to socials and accepted payment options.

**Tasks :**

- [x] Create `footer.html` template
- [x] Include the template in `base.html` 
- [x] Include conatct, socails and payment options
- [x] Test functionality

**Epic :**
[EPIC 5](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/22)

**Comment by tomik-z-cech** [comment]
This was done in commit [5a19fd0](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/5a19fd0b165c1ddda2e5cee6dc27f62fb5d4c213).
