### ISSUE TITLE
USER STORY : Loader

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#26]
As a **Site User** I want to be able to **see if page is working** in the form of **loader that appears when complex task is performed**.

**Acceptance Criteria :**

When I navigate throughout the site when complex actions are being submitted (DB) then the loader appears to ensure me the site didn't freeze.

**Tasks :**

- [x] Include `<div>` loader in `base.html` template
- [x] Style loader with moving content
- [x] Incllude JS logic in forms
- [x] Test functionality

**Epic :**
[EPIC 5](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/22)

**Comment by tomik-z-cech** [comment]
This was done in commit [15a14bd](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/15a14bdcd9066bf13f0a9b1428debed0d879834a).
