### ISSUE TITLE
USER STORY : Toasts

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#27]
As a **Site User** I want to be **informed of results of requests performed** in the form of **toast that appears when complex task is done sucessfully / unsuccessfully**.

**Acceptance Criteria :**

When I navigate throughout the site when complex actions are being submitted (DB) then the toast appears to inform me of the result of action.

**Tasks :**

- [x] Include `<div>` toast in `base.html` template
- [x] Style toast within the page style
- [x] Include JS logic in `base.html`
- [x] Import messages to all `views.py` files when used
- [x] Include meesages in the actual views
- [x] Create toasts templates (success, info, warning, error)
- [x] Test functionality

**Epic :**
[EPIC 5](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/22)

**Comment by tomik-z-cech** [comment]
This was done in commit [be40cc1](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/be40cc1431dc1394c6d53423c605bd844daa3fb7).
