### ISSUE TITLE
USER STORY : Email interface for marketing purposes

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#28]
As a **Site admin**, I need to implement **Mailing interface** to be able to **send emails to all users signed up for email communication**.

**Acceptance Criteria :**

*Staff/SuperUser :*

When I log in with my credentials then I am able to navigate to admin tools section to to create drafts/send emails to all users that are signed up to receive email newsletter.

*Users with no staff or Superuser rank :*

Not able to access that functinality.

**Tasks :**

- [x] Create model "Newsletter" to store all email adresses of users
- [x] Create signal receiver to automatically add users after registration
- [x] Create signal receiver from "profilemanager" app that either adds or deletes user from newsletter model based on their settings
- [x] Adjust `owner.html` template
- [x] Create model for email templates
- [x] Create templates for CRUD of email templates.
- [x] Install Rich Text Field Editor
- [x] Create views
- [x] Adjust owner `urls.py`
- [x] Test functionality

**Epic :**
[EPIC 4](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/15)

**Comment by tomik-z-cech** [comment]
This was done in commit [c05fbef](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/c05fbefce9cd3214b232a4df6eefb26d31efd5e4).
