### ISSUE TITLE
EPIC 6 : User Profile Management

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#29]
**Description :** This epic focuses on management of User Profile

**Details :**

- [ ] USER STORY : Change Details (Phone Number, Email Address, etc.)
- [ ] USER STORY : Delete my account
- [ ] USER STORY : Profile Picture
- [ ] USER STORY : Opt In/Out for Newsletter
