### ISSUE TITLE
USER STORY : Set Up Dependencies

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#3]
As a Developer, I need to register and obtain links for third party services.

**Acceptance Criteria :**

All links of third party services (DB, mail provider, AWS) are obtianed and services set

**Tasks :**

- [x] Register with Neon DB
- [x] Obtain Postgres link
- [x] Refister with Gmail
- [x] Obtain app password
- [x] Register with AWS
- [x] Set AWS
- [x] Obtain AWS links
- [x] Create `env.py` file to keep all secret links and passwords

**Comment by tomik-z-cech** [comment]
Neon DB was selected over ElephantSQL as ElephantSQL only offers PostgreSQL version of 11.19 for newly created free tier instances which causes compatibility issues with psycopg2.

**Comment by tomik-z-cech** [comment]
This was done in commit [76e4e21](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/76e4e21c9676bfe20584fc6a3b10795d0e40dca9).
