### ISSUE TITLE
USER STORY : Change Details (Phone Number, Email Address, etc.)

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#31]
As a **Site User** I can **Update My Details** to **be able to manage my account in case of changes**.

**Acceptance Criteria :**

*Logged in user :*
When I login then I can clearly navigate to "My Details" section where I can change my details.

*Not logged in user :*
Don't have that option as not logged in.

**Tasks :**

- [x] Create a view in `profilemanager` app.
- [x] Read current details from User model
- [x] Create a template for the view.
- [x] Create a form in template
- [x] Create a link to AllAuth email change (as emails are verified)
- [x] Create a link to AllAuth password change
- [x] Test functionality with valid credentials
- [x] Test functionality with invalid credentials

**Epic :**
[EPIC 6](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/30)

**Comment by tomik-z-cech** [comment]
This was done in commit [608f056](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/608f0564333f5a55de3af447b3e0666e4ea4fe0a).
