### ISSUE TITLE
USER STORY : Delete my account

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#32]
As a **Site User** I can **Delete My Account** to **be able to opt out from all services**.

**Acceptance Criteria :**

*Logged in user :*
When I navigate to "my details" then I have the option of delete my account entirely.

*Not logged in user :*
Don't have that option as not logged in.

**Tasks :**

- [x] Update `views.py` in `profilemanager` app
- [x] Update template (delete button)
- [x] Create a modal that informs user of the deletition
- [x] Test functionality with valid credentials

**Epic :**
[EPIC 6](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/30)

**Comment by tomik-z-cech** [comment]
This was done in commit [608f056](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/608f0564333f5a55de3af447b3e0666e4ea4fe0a).
