### ISSUE TITLE
USER STORY : Profile Picture

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#33]
As a **Site User** I can **Change my profile picture** to **add the finishing touch to my profile**.

**Acceptance Criteria :**

*Logged in user :*
When I navigate to "My Details" section then I change my profile picture.

*Not logged in user :*
Don't have that option as not logged in.

**Tasks :**

- [x] Update `views.py` in `profilemanager` to read current profile picture or initials
- [x] Update template
- [x] Add JS logic to display selected profile picture
- [x] Test functionality with valid credentials

**Epic :**
[EPIC 6](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/30)

**Comment by tomik-z-cech** [comment]
This was done in commit [a7bd28a](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/a7bd28a7539cde8d158c8c3a8f95a51aeda3caec).
