### ISSUE TITLE
USER STORY : Opt In/Out for Newsletter

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#34]
As a **Site User** I can **Opt In/Out for Newsletter or other marketing communtiation** to **be able to change my preferences**.

**Acceptance Criteria :**

*Logged in user :*
When I navigate to "My Details" section then I can mark/unmark to receive marketing emails, sms or phone calls.

*Not logged in user :*
Don't have that option as not logged in.

**Tasks :**

- [x] Update `views.py` in `profilemanager` to read current marketing preferences
- [x] Update template
- [x] Test functionality with valid credentials
- [x] Test functionality with invalid credentials

**Epic :**
[EPIC 6](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/30)

**Comment by tomik-z-cech** [comment]
This was done in commit [a7bd28a](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/a7bd28a7539cde8d158c8c3a8f95a51aeda3caec).
