### ISSUE TITLE
USER STORY : Shop Highlights

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#36]
As a **Site User**, I would like to **See Newest and Favourites** on the landing page so I can **see easily what products are after arriving and what are most popular**.

**Acceptance Criteria :**

When I navigate to the site then on landing page I can see featured products, free delivery treshold.

**Tasks :**

- [x] Create app `landing`
- [x] Import modules `Item` and `PostageSettings` to landing views
- [x] Create a "Sign Up for Newsletter" section
- [x] Create template `index.html` 
- [x] Create field for Favourite Items
- [x] Create field for Newes Items
- [x] Test functionality as user

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/35)

**Comment by tomik-z-cech** [comment]
This was done in commit [94932b4](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/94932b44ceee72c1dccff795eab32b6a73bdea0d).
