### ISSUE TITLE
USER STORY : Shop by Category

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#37]
As a **Site User**, I would like to have the shop items sorted by category so I can browse the items faster.

**Acceptance Criteria :**

When I visit the shop with all items then I can see all the categories displayed and when category clicked, items belonging to the category will display.

**Tasks :**

- [x] Create template `shop.html`
- [x] Create a div for all categories
- [x] Update `urls.py` in items
- [x] Load all categories from DB in view
- [x] Test functionality as Site User

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/35)

**Comment by tomik-z-cech** [comment]
This was done in commit [5081a8f](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/5081a8f7ec7c4d8886ccbaeb15f77cf5ddc5635a).
