### ISSUE TITLE
USER STORY : Product Details

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#38]
As a **Site User**, I would like to **see the details of each item** in separate page so **I won't get lost in too much info**.

**Acceptance Criteria :**

When I visit the shop with all items and open details of certain item then I can see all the relevant info per item.

**Tasks :**

- [x] Create template `item_detail.html`
- [x] Create logic for displaying only relevant info to certain item (has sizes, has values ?)
- [x] Create form for adding items to vault
- [x] Create context processor and register in `settings.py`
- [x] Create logic so user can't add negative amount of items to vault or more items than in stock
- [x] Create an option for user to add item to wishlist
- [x] Create an option for user to add item to vault
- [x] Update `urls.py` in items
- [x] Test functionality as Site User

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/35)

**Comment by tomik-z-cech** [comment]
This was done in commit [765f8ad](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/765f8ad074062865599a148bbb882fddb095acd5).
