### ISSUE TITLE
USER STORY : Add to Vault

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#39]
As a **Site User**, I need to be able to **add items to vault** in order to **see the entire order before payment**.  

**Acceptance Criteria :**

When I click "Add to vault" button then the item adds to vault.

**Tasks :**

- [x] Provide user with "Add to Vault" button
- [x] Create view in `views.py`
- [x] Ensure the view communicates with `context_list.py` nested in vault app
- [x] Add logic to prevent doubling of items that are already in vault
- [x] Provide user with message that item was added to the Vault
- [x] Provide user with info how much left for free delivery
- [x] Test functionality as Site User

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/35)

**Comment by tomik-z-cech** [comment]
This was done in commit [06cf6d4](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/06cf6d49910a33306c951d4963dcee42c95d6ee5).
