### ISSUE TITLE
USER STORY : Create Working Django App

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#4]
As a **Site Developer**, I need to set all dependencies, correctly set `settings.py` and create working app in local environment.

**Acceptance Criteria :**

All dependencies are installed, `settings.py` all set for local view and when project is ran locally, symbol of correctly set app is shown (rocket).

**Tasks :**

- [x] Create Virtual Environment
- [x] Install Django
- [x] Install Psycopg2
- [x] Install dj-database
- [x] Insatll AllAuth
- [x] Install Crispy Forms
- [x] Freeze all modules to requirements.txt
- [x] Set-up settings.py

**Epic :**
[EPIC 1](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/1)

**Comment by tomik-z-cech** [comment]
This was done in commit [c8d2a30](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/c8d2a30d6146cf84f0711ad5bdcd3c6ede959b02).
