### ISSUE TITLE
USER STORY : Add to Wishlist

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#40]
As a **Site User**, I need to be able to **add items to my Wishlist** in order to **see keep the items I am interested in separately**.  

**Acceptance Criteria :**

*Logged in User :*

When I click "Add to Wishlist" toggle then the item toggles in Wishlist.

*Not Logged in User :*

Doesn't have that option.

**Tasks :**

- [x] Provide user with "Add to Wishlist" / "Remove from Wishlist" toggle button
- [x] Create view in `views.py`
- [x] Adjust `item_detail.html` template
- [x] Ensure the view communicates with `context_list.py` nested in wishlist app
- [x] Add logic to toggle item in Wishlist
- [x] Provide user with message that item was added / removed to / from the Wishlist
- [x] Protect the view to only logged in users
- [x] Test functionality as Logged in User
- [x] Test functionality as Not Logged in User

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/35)

**Comment by tomik-z-cech** [comment]
This was done in commit [618624a](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/618624a73180d51eaeb62a656790f0b295726df1).
