### ISSUE TITLE
USER STORY :  Comment on Products

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#41]
As a **Site User** I can **Comment on Items** to **share my opinion**.

**Acceptance Criteria :**

*Logged in user :*
When **I navigate to item detail in shop** then I am able to **add comment on the relevant item**.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Adjust ItemDetailView view in `views.py` with `def post`
- [x] Create commenting form in `item_detail.html` template
- [x] Provide user with "submit comment" button
- [x] Only add the form visibility to logged in users
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/35)

**Comment by tomik-z-cech** [comment]
This was done in commit [aaacdb9](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/aaacdb93817745397d28e8b3cd63dcafe8162939).
