### ISSUE TITLE
USER STORY : See Comments of others

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#42]
As a **Site User** I can **see other comments on Items** to **read other Users opinions**.

**Acceptance Criteria :**

*Logged in user :*
When I open item detail then I am able to see other people comments.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Adjuts `views.py`
- [x] Create "comments section" in `item_details.html`
- [x] Iterate through comments to display them in `item_details.html`
- [x] Ensure the comments visibility is only for logged in users
- [x] Paginate the comments
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/35)

**Comment by tomik-z-cech** [comment]
This was done in commit [8c48498](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/8c484989ced1eb6a400534a8da2aadb6a89b4d98).
