### ISSUE TITLE
USER STORY : Display Wishlist Items

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#44]
As a **Site User**, I can **display items in My Wishlist** in order to **manage the items**.

**Acceptance Criteria :**

*Logged In User :*

When I log in and navigate to "My Wishlist" section then I can clearly see all items in the wishlist .

*Not Logged In User :*

Doesn't have that option.

**Tasks :**

- [x] Create Wishlist app `urls.py`
- [x] Create view for displaing the Wishlist in `views.py`
- [x] Create `wishlist.html` template
- [x] Provide user with clear list of items including image, name, price and description of item 
- [x] Test functionality as Logged In User
- [x] Test functionality as Not Logged In User

**Epic :**
[EPIC 8](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/43)

**Comment by tomik-z-cech** [comment]
This was done in commit [b71e9f9](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/b71e9f93064e251ebca34ca52ecf6e4e2fa0e672).
