### ISSUE TITLE
USER STORY : Remove Items from Wishlist

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#45]
As a **Site User**, I can **remove items from My Wishlist one by one** in order to **manage the items in the Wishlist**.

**Acceptance Criteria :**

*Logged In User :*

When I log in and navigate to "My Wishlist" section then I can clearly see an option to delete item from Wishlist .

*Not Logged In User :*

Doesn't have that option.

**Tasks :**

- [x] Create view for deleting item in `views.py`
- [x] Provide user with clearly located button for deleting item
- [x] Provide User with message of confirmation
- [x] Test functionality as Logged In User
- [x] Test functionality as Not Logged In User

**Epic :**
[EPIC 8](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/43)

**Comment by tomik-z-cech** [comment]
This was done in commit [15910d7](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/15910d7bb677671a70b3253290957915f93002ab).
