### ISSUE TITLE
USER STORY : Clear Wishlist

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#46]
As a **Site User**, I can **delete all items in My Wishlist** in order to **manage the items**.

**Acceptance Criteria :**

*Logged In User :*

When I log in and navigate to "My Wishlist" section then I can clearly see option to delete all items from the Wishlist .

*Not Logged In User :*

Doesn't have that option.

**Tasks :**

- [x] Create proper view in `views.py`
- [x] Provide user with clear option of clearing their Wishlist
- [x] Provide User with confirming Modal
- [x] Provide User with confirmation message 
- [x] Test functionality as Logged In User
- [x] Test functionality as Not Logged In User

**Epic :**
[EPIC 8](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/43)

**Comment by tomik-z-cech** [comment]
This was done in commit [84e5561](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/84e55610bf98f797529552d0dfd6f5df50ecdcd2).
