### ISSUE TITLE
USER STORY : Display content of Vault

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#48]
As a **Site User**, I can **display items in Vault** in order to **manage the items**.

**Acceptance Criteria :**

When I visit the site and navigate to "Vault" section then I can clearly see all items in the Vault .

**Tasks :**

- [x] Create Vault app `urls.py`
- [x] Create view for displaing the Vault in `views.py`
- [x] Create `vault.html` template
- [x] Provide user with clear list of items including image, name, price and description of each item in Vault
- [x] Provide User with clear information about free delivery
- [x] Provide user with clear Total Vault Amount at the bottom of page
- [x] Test functionality as Logged In User
- [x] Test functionality as Not Logged In User

**Epic :**
[EPIC 9](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/47)

**Comment by tomik-z-cech** [comment]
This was done in commit [d407252](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/d40725233ee4938ac42d36a9a8505bf096f3e737).
