### ISSUE TITLE
USER STORY : Adjust amounts of items in Vault

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#49]
As a **Site User**, I can **adjust amount of each item in Vault** in order to **manage the items before proceeding to Checkout**.

**Acceptance Criteria :**

When I visit the site and navigate to "Vault" section then I can clearly see amount of each item and I have an option to adjust or remove the item from the Vault .

**Tasks :**

- [x] Create a post method of displaying the Vault for adjusting amounts
- [x] Create a view for deleting items from Vault one by one
- [x] Provide User with "Remove" button that removes an item from Vault
- [x] Provide User with number input field for adjusting the amounts
- [x] Prepopulate each field with the amount selected
- [x] Create logic so User can't submit different than a valid quantity number
- [x] Provide user with message that Vault has / hasn't been updated
- [x] Test functionality as Logged In User
- [x] Test functionality as Not Logged In User

**Epic :**
[EPIC 9](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/47)

**Comment by tomik-z-cech** [comment]
This was done in commit [f90e353](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/f90e353901b79ed1e8083944ebcbf61716692e1d).
