### ISSUE TITLE
USER STORY : Deploy to Heroku

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#5]
As a **Site Developer** I need to create a working Heroku deployement.

**Acceptance Criteria :**

Working Heroku Deployment, when first deployed site accesed, it gives hint of correctly installed Django App (DEBUG = True). Create if statement in settings.py for DEBUG = False when deployed.

**Tasks :**

- [x] Create Heroku App
- [x] Link with GitHub
- [x] Set up Vars
- [x] Create first deployment
- [x] Fix issues (if any)
- [x] Set if/else statement for `DEBUG = False`

**Epic :**
[EPIC 1](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/1)

**Comment by tomik-z-cech** [comment]
This was done in commit [c8d2a30](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/c8d2a30d6146cf84f0711ad5bdcd3c6ede959b02).
