### ISSUE TITLE
USER STORY : Clear the Vault

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#50]
As a **Site User**, I can **delete all items in Vault** in order to **manage the items**.

**Acceptance Criteria :**

When I visit the site and navigate to "Vault" section then I can clearly see option to delete all items from the Vault .

**Tasks :**

- [x] Create proper view in `views.py`
- [x] Provide user with clear option of clearing their Vault
- [x] Provide User with confirming Modal
- [x] Provide User with confirmation message 
- [x] Test functionality as Logged In User
- [x] Test functionality as Not Logged In User

**Epic :**
[EPIC 9](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/47)

**Comment by tomik-z-cech** [comment]
This was done in commit [b0af0c3](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/b0af0c39015731013707ebca089e5854f4619573).
