### ISSUE TITLE
USER STORY : Proceed to Checkout

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#51]
As a **Site User**, I can **proceed to Checkout** in order to **pay for items in my Vault**.

**Acceptance Criteria :**

When I visit the site and navigate to "Vault" and I am happy with the content then I can clearly proceed to Checkout .

**Tasks :**

- [x] Create Checkout app `urls.py`
- [x] Provide User with "Proceed to Checkout" button
- [x] Test functionality as Logged In User
- [x] Test functionality as Not Logged In User

**Epic :**
[EPIC 9](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/47)

**Comment by tomik-z-cech** [comment]
This was done in commit [ea6f86e](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/ea6f86e2d27f280041f8d4c6b6deca2348392418).
