### ISSUE TITLE
USER STORY : Vault management toasts

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#52]
As a **Site User**, I can **see message that indicates Vault action along all items that are in Vault** in order to **be informed and have an idea what's in Vault without opening the Vault**.

**Acceptance Criteria :**

When I submit any "Vault" section action (add, delete, adjust) then I can clearly see in form of toast all items in the Vault, the total and postage treshold .

**Tasks :**

- [x] Create devoted Vault level of messages in `base.html`
- [x] Create devoted template for Vault messages
- [x] Create `if / else` statement for displaying postage info
- [x] Create `if / else` statement for displaying content
- [x] Create `for loop` for displaying all items
- [x] Provide user with clear Total Vault Amount at the bottom of toast
- [x] Test functionality as Logged In User
- [x] Test functionality as Not Logged In User

**Epic :**
[EPIC 9](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/47)

**Comment by tomik-z-cech** [comment]
This was done in commit [affb550](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/affb550bba590c36096eb6d201122cb038d64f81).
