### ISSUE TITLE
USER STORY : Shipping Details

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#54]
As a **Site User**, I can provide shipping details in order to inform the shop where to send my purchase.

**Acceptance Criteria :**

*Loged In User :*
When I navigate to "Secure Checkout" then I can enter / change (if provided in "My Details") shippings details .

*Not Loged In User :*
When I navigate to "Secure Checkout" then I can enter shippings details .

**Tasks :**

- [x] Create OrderForm in `forms.py` in chcekout
- [x] Generate the form in `chcekout.html` template
- [x] Create JS functionality and animation for form validation
- [x] Test functionality as Loged In User
- [x] Test functionality as Not Loged In User

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/53)

**Comment by tomik-z-cech** [comment]
This was done in commit [bbe7628](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/bbe7628cc0bcf618ba307c8b9084157e08c34c7c).
