### ISSUE TITLE
USER STORY : Vouchers

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#55]
As a **Site User**, I have an option to redeem dicount codes in order to get discount on my purchase.

**Acceptance Criteria :**

When I navigate to "Secure Checkout" then I have an option to redeem dicount code in clear manner.

**Tasks :**

- [x] Create a form for redeeming vouchers `forms.py` in checkout
- [x] Implement form for redeeming vouchers in`checkout.html` template
- [x] Create logic to compare code entered by User with codes in database
- [x] Update price of order accordingly
- [x] Create clear feedback to User
- [x] Test functionality as logged in User
- [x] Test functionality as not logged in User

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/53)

**Comment by tomik-z-cech** [comment]
This was done in commit [0fbac68](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/0fbac6828c0efd40a85cfc957e6787acdaf51aba).
