### ISSUE TITLE
USER STORY : Stripe and Webhooks Setup

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#56]
As a **Site Admin**, I need to be able to process the order functions even in event of failure in order to ensure no paying customer is left without goods.

**Acceptance Criteria :**

When User provides valid payment media number but connection is interrupted for some reason during the confirmation process then all other functions (saving order, email, invoice) needs to proceed as normal via webhooks.

**Tasks :**

- [x] Create webhooks handlers
- [x] Set webhooks endpoint on stripe.com
- [x] Copy functionality from sucesfull checkout view to webhooks
- [x] Adjsut the functionality so saved info based on stripe metadata
- [x] Test locally via stripe CLI
- [x] Test functionality as logged in User
- [x] Test functionality as not logged in User

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/53)

**Comment by tomik-z-cech** [comment]
This was done in commit [9d07b91](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/9d07b912e0be257efa606122f476a791748ac300).
