### ISSUE TITLE
USER STORY : Payment

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#57]
As a **Site User**, I have an option providing payment details in order to pay for my goods.

**Acceptance Criteria :**

When I navigate to "Secure Checkout" and fill in all the required info then I can pay by providing payment media number.

**Tasks :**

- [x] Implement `stripe.js` in `base.html` template
- [x] Create and implement `stripe_elements.js` in `checkout.html` template
- [x] Create element for mounting Stripe payment field 
- [x] Create element for mounting error messages
- [x] Test functionality as logged in User
- [x] Test functionality as not logged in User

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/53)

**Comment by tomik-z-cech** [comment]
This was done in commit [0ab3c1e](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/0ab3c1e6966f2454189670aa4ba0ec9e135e9544).
