### ISSUE TITLE
USER STORY : Invoice Generator

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#58]
As a **Site Admin**, I need to be able to generate invoice in `*.pdf` format in order the invoice being attached to the confirmation email.

**Acceptance Criteria :**

When User sucessfully proceeds through checkout the invoice in `*.pdf` needs to be generated based on order details adn saved to database.

**Tasks :**

- [x] Gather all details needed for invoice from the order
- [x] Count other necessary values (VAT, subtotal excluding VAT)
- [x] Get a timestamp of now.
- [x] Install django Canvas
- [x] Draw invoice based on provided info
- [x] Save invoice into database
- [x] Test functionality as logged in User
- [x] Test functionality as not logged in User

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/53)

**Comment by tomik-z-cech** [comment]
This was done in commit [7395bb8](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/7395bb80231ab9d561153d54931fdd3fa7de11fe).
