### ISSUE TITLE
USER STORY : Confirmation Email

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#59]
As a **Site User**, I do get confirmation email in order to know the transaction was sucessfull.

**Acceptance Criteria :**

When I sucessfully proceed through payment, then I am notified via email about my purchase.

**Tasks :**

- [x] Import necessary modules into `views.py`
- [x] Create email template
- [x] Create logic of passing variables into template 
- [x] Create logic of attaching invoice to email
- [x] Test functionality as logged in User
- [x] Test functionality as not logged in User

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/53)

**Comment by tomik-z-cech** [comment]
This was done in commit [2b5929a](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/2b5929accb57289a57dd7a6deb64f81ecc04a228).
