### ISSUE TITLE
USER STORY : Stock Update

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#60]
As a **Site Admin**, I need to be able to update stock amounts after every purchase in order the manage the inventory.

**Acceptance Criteria :**

When User sucessfully proceeds through checkout then the amounts of stock levels are updated.

**Tasks :**

- [x] Iterate through Vault after purchase and update each item stock level
- [x] Test functionality as logged in User
- [x] Test functionality as not logged in User

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/53)

**Comment by tomik-z-cech** [comment]
This was done in commit [f901a9c](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/f901a9cf9609396bd325d29f2319e886f5536043).
