### ISSUE TITLE
USER STORY : Checkout Page

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#61]
As a **Site User**, I can see checkout page so I know exactly what am I being charged for.

**Acceptance Criteria :**

When I add my desired products into Vault and click "secure Payment" then a payment page loads up.

**Tasks :**

- [x] Create a checkout view in checkout `views.py` 
- [x] Update checkout `urls.py`
- [x] Provide User with input fields for shipping details form
- [x] Prefill shipping details form if User logged in
- [x] Provide User with delivery option selection
- [x] Provide User with Redeem Voucher section
- [x] Provide User with Payment form
- [x] Test functionality as logged in User
- [x] Test functionality as not logged in User

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/53)

**Comment by tomik-z-cech** [comment]
This was done in commit [8b3724a](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/8b3724a2ab7034874a20588ff9ca25fa3bd12cca).
