### ISSUE TITLE
USER STORY : Save info

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#62]
As a **Site User**, I can save provided shipping info in order the form being prefilled with next order.

**Acceptance Criteria :**

*Loged In User :*
When I navigate to "Secure Checkout" and  provide new / different shipping info then I have an option to save the details provided.

*Not Loged In User :*
Doesn't have that option.

**Tasks :**

- [x] Create save info checkbox in `checkout.html` template
- [x] Provide saving logic in POST request Checkout view
- [x] Provide the same info (details, save info option) to Stripe payment intent for webhooks use
- [x] Test functionality as Loged In User
- [x] Test functionality as Not Loged In User

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/53)

**Comment by tomik-z-cech** [comment]
This was done in commit [9c34d7d](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/9c34d7d35134ff1e957e435e64d248ee09e8fb6d).
