### ISSUE TITLE
USER STORY : Delivery Options

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#63]
As a **Site User**, I can choose between standard and express delivery in order to control the speed of delivery.

**Acceptance Criteria :**

When I navigate to "Secure Checkout" then I can choose my preferred delivery option.

**Tasks :**

- [x] Create a radio selection for user between delivery options in `checkout.html` template
- [x] Provide user with clear cost of each delivery option
- [x] Create logic for free delivery when over treshold
- [x] Create JS logic for the total price update everytime delivery option is changed
- [x] Test functionality as logged in User
- [x] Test functionality as not logged in User

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/53)

**Comment by tomik-z-cech** [comment]
This was done in commit [0ab3c1e](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/0ab3c1e6966f2454189670aa4ba0ec9e135e9544).
