### ISSUE TITLE
USER STORY : Success Page

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#64]
As a **Site User**, I can clarly see sucess page in order to know my order went through without checking my emails.

**Acceptance Criteria :**

When I sucessfully proceed with payment then I can see success page containing order details, order number and estimated delivery dates.

**Tasks :**

- [x] Create `checkout-ok.html` template
- [x] Create a view for checkout success
- [x] Adjust `urls.py` in checkout
- [x] Test functionality as logged in User
- [x] Test functionality as not logged in User

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/53)

**Comment by tomik-z-cech** [comment]
This was done in commit [c7d638c](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/c7d638cc91c9e8cc931d036b574f4737b9b192e1).
