### ISSUE TITLE
USER STORY : Accessing Order History

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#66]
As a **Site User**, I can access my own past orders in case of needing them in future. 

**Acceptance Criteria :**

*Loged In User :*
When I navigate to "Order History" section then I clearly see all my past orders then  .

*Not Loged in User :*

Doesn't have that option.

**Tasks :**

- [x] Create app `history`
- [x] Register in settings.py
- [x] Create and update local `urls.py`
- [x] Update global `urls.py`
- [x] Create a logic in `views.py` that orders of loged in user will display
- [x] Protect the view for only loged in users
- [x] Test functionality as loged in user
- [x] Test functionality as not loged in user

**Epic :**
[EPIC 11](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/65)

**Comment by tomik-z-cech** [comment]
This was done in commit [3b301fc](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/3b301fc1521ad8851a4392ab00337a54ac8a402e).
