### ISSUE TITLE
USER   STORY : Define Database Schema

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#7]
As a **Developer**, I need to create databse schema that fits the purpose of the project and also create all the modular apps that will be used in the project.

**Acceptance Criteria :**

All Django apps are created and database schema in place to adhere to.

**Tasks :**

- [x] Create Landing app + models
- [x] Create Owner app + models
- [x] Create Items app + models
- [x] Create Profilemanager app + models
- [x] Create Vault app + models
- [x] Create Checkout app + models
- [x] Create Wishlist app + models
- [x] Create Database Schema that shows names of tables, fileds and relationships

**Epic :**
[EPIC 2](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/6)

**Comment by tomik-z-cech** [comment]
This was done in commit [1d2929d](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/1d2929d2a31e281b2890acd9827199d2101d7811).
