### ISSUE TITLE
USER STORY : Search Bar in header of page

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#70]
As a **Site User** I am able to **use search function** through Categories, Items and Item descriptionsin order to **quickly find what am I looking for**.

**Acceptance Criteria :**

When I navigate to any page of the site then I can see the search bar located in the header.

**Tasks :**

- [x] Create search logic in `views.py` of landing app.
- [x] Provide users clearly with what fields they are searching
- [x] Provide users with text input field
- [x] Provide user with search button
- [x] User shouldn't be able to submit empty string as search criteria
- [x] Test functionality

**Epic :**
[EPIC 12](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/69)

**Comment by tomik-z-cech** [comment]
This was done in commit [93a786e](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/93a786e4d8c00f1b8cdf8754843cd3f83bdf2549).
