### ISSUE TITLE
USER STORY : Like / Dislike Items of Shop

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#72]
As a **Site User** I can **Like / Dislike particular Item in Shop**in order to **express my opinion**.

**Acceptance Criteria :**

*Logged in user :*
When I navigate to shop and open detail of Item then I am able to like or dislike the Item.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Adjust `views.py`
- [x] Provide user with "like / dislike" button in `item_detail.html`
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/35)

**Comment by tomik-z-cech** [comment]
This was done in commit [35a4884](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/35a48849bb86b7ace9b376d3d8e645dc4954d472).
