### ISSUE TITLE
USER STORY : Intuitive Navigation

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#74]
As a **Site Developer**, I need to insure easy navigation throughout the site

**Acceptance Criteria :**

When user does access the site then all links and actions are intuitive and don't need too much thinking, design is responsive on all device sizes.

**Tasks :**

- [x] Style Landing Page for various devices
- [x] Style Checkout for various devices
- [x] Style History for various devices
- [x] Style Items for various devices
- [x] Style Owner for various devices
- [x] Style Profilemanager for various devices
- [x] Style Vault for various devices
- [x] Style Wishlist for various devices
- [x] Style Forms for various devices
- [x] Style Modals for various devices
- [x] Test design as logged in user on various devices
- [x] Test design as not logged in user on various devices
- [x] Test responsiveness as logged in or not logged in user on various devices

**Epic :**
[EPIC 13](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/73)

**Comment by tomik-z-cech** [comment]
This was done in commit [5707b7b](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/5707b7b967861552ed18de3f89c954560dd2f623).
