### ISSUE TITLE
USER STORY : Color Scheme

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#75]
As a **Site Developer**, I need to insure easy navigation throughout the site

**Acceptance Criteria :**

When user does access the site then all links and actions are intuitive and don't need too much thinking, design is responsive on all device sizes.

**Tasks :**

- [x] Color Landing Page for various devices
- [x] Color Checkout for various devices
- [x] Color History for various devices
- [x] Color Items for various devices
- [x] Color Owner for various devices
- [x] Color Profilemanager for various devices
- [x] Color Vault for various devices
- [x] Color Wishlist for various devices
- [x] Color Forms for various devices
- [x] Color Modals for various devices
- [x] Check design as logged in user on various devices
- [x] Check design as not logged in user on various devices

**Epic :**
[EPIC 13](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/73)

**Comment by tomik-z-cech** [comment]
This was done in commit [5707b7b](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/5707b7b967861552ed18de3f89c954560dd2f623).
