### ISSUE TITLE
USER STORY : WAVE Compatibility

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#76]
As a **Site Developer**, I need to insure easy navigation throughout the site for users in need of ease of access

**Acceptance Criteria :**

When user in need of ease of acces tools does access the site then all links and actions are labelled and intuitive and don't confuse the User.

**Tasks :**

- [x] Ensure passing grade on WCAG AAA - WAVE - Landing Page
- [x] Ensure passing grade on WCAG AAA - WAVE - Checkout
- [x] Ensure passing grade on WCAG AAA - WAVE - History
- [x] Ensure passing grade on WCAG AAA - WAVE - Items
- [x] Ensure passing grade on WCAG AAA - WAVE - Owner
- [x] Ensure passing grade on WCAG AAA - WAVE - Profilemanager
- [x] Ensure passing grade on WCAG AAA - WAVE - Vault
- [x] Ensure passing grade on WCAG AAA - WAVE - Wishlist
- [x] Ensure passing grade on WCAG AAA - WAVE - Forms
- [x] Ensure passing grade on WCAG AAA - WAVE - Modals
- [x] Ensure passing grade on WCAG AAA - Test WAVE as logged in user
- [x] Ensure passing grade on WCAG AAA - Test WAVE as not logged in user
- [x] Ensure passing grade on WCAG AAA - Test WAVE on various devices (screen sizes)

**Epic :**
[EPIC 13](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/73)

**Comment by tomik-z-cech** [comment]
This was done in commit [2043e49](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/2043e497eef8b727f24fe90bf1f014b6756b9615).
