### ISSUE TITLE
USER STORY : Create database realtionships

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#8]
As a **Developer**, I need to define relatinships between models and import the relationships into working apps models.

**Acceptance Criteria :**

All models are working with the relationships defined, all models that are related to other app models are linked via import statements.

**Tasks :**

- [x] Create models for all apps.
- [x] Set relationships between them via import statements (if applicable).
- [x] Create databse instance in Neon DB
- [x] Connect with Neon DB server via URL given by Neon
- [x] Create S3 bucket with AWS
- [x] Connect with AWS server via keys given by AWS
- [x] Run `python manage.py makemigrations`
- [x] Run `python manage.py migrate`

**Epic :**
[EPIC 2](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/6)

**Comment by tomik-z-cech** [comment]
This was done in commit [1d2929d](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/1d2929d2a31e281b2890acd9827199d2101d7811).
