### ISSUE TITLE
USER STORY : Implement Data Validation in Models

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#9]
As a Developer, I need implement data validation rules within Ohm-Azing Componenets database models.

**Acceptance Criteria :**

All values inserted into database are the correct values and types, all applicable fileds are all set to be required or/and to be unique or/and nullable/not nullable.

**Tasks :**

- [x] Set correct data type for all fileds
- [x] Set all required fields to `required = True`
- [x] Set all required fileds that can be nullable to `null = True`
- [x] Set all required fileds that have to be unique (username) `unique = True`
- [x] Create SuperUser
- [x] Test data type by inserting test data into databse

**Epic :**
[EPIC 2](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/6)

**Comment by tomik-z-cech** [comment]
This was done in commit [1d2929d](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/commit/1d2929d2a31e281b2890acd9827199d2101d7811).
