### ISSUE TITLE
USER STORY : Postage label printing

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#97]
As a **Site Admin**, I can **print postage label on printing page** to be able to **Effortlessly print postage labels**.

**Acceptance Criteria :**

*Only as Superuser* :
When I log in as Superuser and navigate to Admin Tools then I can select order to view and print postage label based on order details.

**Tasks :**
- [ ] Adjust `owner.html` template
- [ ] Create printing template
- [ ] Create new view in `views.py` in owner app
- [ ] Adjust `urls.py` in owner app
- [ ] Test functionality as Site Admin

**Epic :**
[EPIC ](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/15)

**Comment by tomik-z-cech** [comment]
This feature won't be done in this project.
