### ISSUE TITLE
USER STORY : Order status emails

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#98]
As a **Site Admin**, I can **mark orders as accepted, pending, fulfilled** to be able to **keep customers informed of the status of their order**.

**Acceptance Criteria :**

*Only as Superuser* :
When I navigate to Admin Tools and Invoices then I can see status of the order and I can change the status, customer is then notified via email of the progress. 

**Tasks :**
- [ ] Adjust `owner.html` template
- [ ] Create printing template
- [ ] Create new view in `views.py` in owner app
- [ ] Adjust `urls.py` in owner app
- [ ] Test functionlity as Site Admin

**Epic :**
[EPIC ](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/15)

**Comment by tomik-z-cech** [comment]
This feature won't be done in this project.
