### ISSUE TITLE
USER STORY : Frequently bought together

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP5-Ohm-Azing-Components#99]
As a **Site User**, I **can see what items are bought together** to be able to **what else can I buy for the same project**.

**Acceptance Criteria :**

When I navigate to the shop and item detail, I can see what items are frequenly bought with the item that I am viewing.

**Tasks :**
- [ ] Adjust `views.py` in shop
- [ ] Adjust `item_detail.html` template
- [ ] Test functionality as Loged In User
- [ ] Test functionality as Not Loged In User

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP5-Ohm-Azing-Components/issues/35)

**Comment by tomik-z-cech** [comment]
This feature won't be done in this project.
